name: Generate PacMan Animation

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install pillow

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Run PacMan script
      run: python assets/pacMan.py

    - name: Create GIF from PNGs
      run: convert -delay 10 -loop 0 assets/pacman/*.png assets/pacman/pacman.gif

    - name: Commit generated GIF
      run:
        git config joaovfe "GitHub Actions"
        git config joaovitorfespindola@gmail.com "github-actions@github.com"
        git add assets/pacman/pacman.gif
        git commit -m "Add generated Pacman GIF"
        git push origin main